
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'cp_dbt_standard_package'
version: '2.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
  +transient: false

  cp_dbt_standard_package:
    +enabled: "{{ env_var('DBT_ARTIFACTS_DATABASE', 'not-set') != 'not-set'}}"
    +enabled: "{{ env_var('DBT_ARTIFACTS_SCHEMA', 'not-set') != 'not-set'}}"
    +database: "{{ env_var('DBT_ARTIFACTS_DATABASE','not-set')}}"
    +schema: "{{ env_var('DBT_ARTIFACTS_SCHEMA','not-set')}}"

#hook
on-run-end:
  - "{{dbt_artifacts.upload_results(results) if ((env_var('DBT_ARTIFACTS_DATABASE', 'not-set') != 'not-set' ) && (env_var('DBT_ARTIFACTS_SCHEMA', 'not-set') != 'not-set' ))}}"
